### ISSUE TITLE
Listing Rite Aid location that doesn’t exist on Rite Aid appointment site

### ISSUE THREAD

**Issue by avidrissman** [GUI/covid-vaccine-spotter#109]
A search for “10011” is yielding a listing for “Rite Aid - 501 6th Avenue, New York, NY, 10011” with appointments supposedly available. Yet, searching for “10011” on the Rite Aid site doesn’t yield any location at that address, not even one that has no appointment slots.

**Comment by avidrissman** [comment]
To clarify:

The Rite Aid search is returning a Rite Aid location that does not show up on their vaccine search and doesn’t appear to be vaccinating people.

**Comment by babbitt** [comment]
@avidrissman did some digging for you and unfortunately it looks like this might be an issue out of our hands. 
I'm not an active contributor (yet) but it appears that the data comes in through an internal RiteAid API
https://github.com/GUI/covid-vaccine-spotter/blob/ef2007436a5d2ea26001aec1089b62a19eb9b0dd/src/providers/riteAid/appointments.js#L66
I grabbed the storename from @Lynne-Daniels comment (thank you!) and got the following
https://www.riteaid.com/services/ext/v2/vaccine/checkSlots?storeNumber=04261
![image](https://user-images.githubusercontent.com/10392896/113039791-13371200-9166-11eb-988a-0e369dbe90ed.png)
I can only guess what slot 1&2 mean (I'm guessing dose one vs two), but it appears that they're reporting this store has vaccines. Hence the vaccine spotter is too. 

Unfortunately not sure there's much we can do about this one :(

(P.S. Did some digging on the RiteAid side of things and when you search the zip 10011 on their site it doesn't even show you any locations, which there definitely are since if you add one and search 10012 you get 10 stores. So I'd imagine there's some weirdness in the 10011 twilight zone. Maybe just give the pharmacy a call and see if they're offering appointments)

**Comment by babbitt** [comment]
It may be outside the scope of this project but if that "messing around in the console" is something we can package up ([maybe as a bookmark](https://superuser.com/questions/529859/turn-javascript-into-bookmark-or-bookmarklet/1370252)) we could probably help people get more appointments

**Comment by avidrissman** [comment]
FYI we have more data. The appointments are real, but the reason the Rite Aid store isn’t listed is because it’s being closed in two weeks. All the remaining appointment slots are filled up, so I’m not sure any project to help people “mess around in the console” will be a good use of time.

**Comment by terrillfrantz** [comment]
To see if slots **may be ** available go to your browser and put in this url https://www.riteaid.com/services/ext/v2/vaccine/checkSlots?storeNumber=####
where #### is the store number you are interested in.  

You will see either: 
{"Data":{"slots":{"1":true,"2":false}},"Status":"SUCCESS","ErrCde":null,"ErrMsg":null,"ErrMsgDtl":null}  
OR 
{"Data":{"slots":{"1":false,"2":false}},"Status":"SUCCESS","ErrCde":null,"ErrMsg":null,"ErrMsgDtl":null}
OR 
blank

if you get the first one with Data.slots[1] = true
then appointments **may** be available.
if you get either of the other two, appointments are **definitely not *** available and not waste your time going through the riteaid.com website process.

Of course, just write a script to poll this url to make life even easier.  Worked great for me!  I polled for three days then suddenly got the Data.slots[1]=true and went to the riateaid website....mission accomplished!

**Comment by GUI** [comment]
Closing this as fixed by https://github.com/GUI/covid-vaccine-spotter/commit/a5d064d7167298fd0d73a567dd996be2d0f3021d. Now that we refresh the store's locations, we should be reflecting what Rite Aid's own site says for appointments.
