### ISSUE TITLE
missing walmart availability (WA)

### ISSUE THREAD

**Issue by jxchong** [GUI/covid-vaccine-spotter#118]
Identified at least one Walmart in WA that has a day's worth of appointments posted but you're not picking up through multiple update cycles. Presumably it's because `"carries_vaccine": false` ?

```
  "properties": {
    "id": 800767,
    "url": "https://www.walmart.com/pharmacy/clinical-services/immunization/scheduled?imzType=covid",
    "city": "Lynnwood",
    "name": "Lynnwood Neighborhood Market",
    "state": "WA",
    "address": "17222 Highway 99",
    "provider": "walmart",
    "time_zone": "America/Los_Angeles",
    "postal_code": "98037",
    "appointments": null,
    "provider_brand": "walmart",
    "carries_vaccine": false,
    "appointment_types": null,
    "provider_brand_id": 70,
    "provider_brand_name": "Walmart",
    "provider_location_id": "5678",
    "appointments_available": null,
    "appointment_vaccine_types": null,
    "appointments_last_fetched": null,
    "appointments_last_modified": null,
    "appointments_available_all_doses": null,
    "appointments_available_2nd_dose_only": null
  }
```

**Comment by jxchong** [comment]
Related to #82 but I thought you fixed it?

**Comment by ckugel** [comment]
could be that phoenix was misspelled in providers/Walmart/Store.js on line 91

**Comment by GUI** [comment]
@jxchong: Thanks for letting me know about this! It looks like the Walmart store refresh was sometimes dying due to sporadic errors in requesting their data (I was getting 500 errors back). I've tried to make this more resilient to failures in https://github.com/GUI/covid-vaccine-spotter/commit/5b201fdf036289a1a71fe419ff2576fea8681fcd by retrying the failed requests (this seems to largely solve the issue), and not making a single store lookup fatal (so even if errors are countered, the overall refresh process can still continue to other stores).

This has now successfully run through the store refresh process a few times, so I'm hoping this should be fixed. Sorry for the issue, but I'll try to keep a closer eye on some of my monitoring. And give a shout if you see anything amiss. Thanks again for reporting this!
