### ISSUE TITLE
Costco availability not being picked up

### ISSUE THREAD

**Issue by jxchong** [GUI/covid-vaccine-spotter#164]
Costco in zip 98382 has availability which you're not getting, and 4 other locations in the Seattle metro area had availability within the last 2 hours.

**Comment by jxchong** [comment]
It's because they introduced a new serviceId (119).

**Comment by GUI** [comment]
I believe this should be working for Washington again. I think the issue today may have been slightly different from the original issue you reported a couple days ago, but it looks like Costco has finally unified all of their booking for all states under a single link. So that's actually good news as it simplifies a lot of things, but it tripped up my store updating/scanning process for extracting some of the other IDs necessary for appointment booking. I think this should be fixed by https://github.com/GUI/covid-vaccine-spotter/commit/aa3242de5ea48a09016d67e038597276b6abb0b9, and I'm now seeing Washington locations being picked up that weren't previously. So while I think this is working, I've seen some other small changes on their end that I'd like to dig more into just to double check. I'll try to investigate more tomorrow, but give a shout in the meantime if you notice anything else amiss. Thanks again for the heads up!

**Comment by jxchong** [comment]
Yeah today's change is different from the one I originally filed... so we have the fun of redoing the scraper twice in one week. 🤦🏻‍♀️

**Comment by jxchong** [comment]
I think they haven't necessarily changed the offsite location link though it's hard to say for sure due to the J&J situation. https://book-costcopharmacy.appointment-plus.com/d0m1slrg/#/
