### ISSUE TITLE
CVS showing false positives

### ISSUE THREAD

**Issue by tsfischer** [GUI/covid-vaccine-spotter#169]
CVS is showing MANY appointments in the Twin Cities area. However when I go to their website, as soon as I enter "Minnesota" they say "no appointments available.

**Comment by tsfischer** [comment]
Here's a screencap video of what I'm seeing:

https://user-images.githubusercontent.com/12765220/116491148-d2aedf00-a85e-11eb-90ea-f755e268dd8e.mov

**Comment by kilo-WATT** [comment]
Try using this link instead: https://www.cvs.com/vaccine/intake/store/cvd-schedule?icid=cvd_bstr_only

The initial drop down seems on the first landing page says no appointments but if you click the link labeled "Schedule second dose" it allows you to select schedule first dose later and I saw appointments available for the zip code you posted.

**Comment by GUI** [comment]
I'm hoping this should be addressed by https://github.com/GUI/covid-vaccine-spotter/pull/172. We now have a more official source of data for CVS that CVS has said should be lined up with the rest of their systems.

I have also changed the booking link to your suggestion, @kilo-WATT, since I've also heard from some other developers that it's maybe less subject to some caching issues with the front city page. But I'm not totally sure about that, it also sounds like there may have been some CVS maintenance going on. But hopefully the more direct booking link will be helpful in any case (a couple less clicks).

But thanks for brining this up! Hopefully this will be better now, but as always, give a shout if you still see any oddities.
