### ISSUE TITLE
Time zone display can be wonky

### ISSUE THREAD

**Issue by GUI** [GUI/covid-vaccine-spotter#49]
After the latest updates, the time zone handling appears sporadically broken. I had previously been using [time-elements](https://github.com/github/time-elements) to handle rendering a static time on the page, but having it update to the client's time zone. However, with the switch to Nuxt/Vue for the website, it seems like this doesn't always behave as expected. I suspect this might be fighting with Nuxt or Vue's own template rendering and refreshing. It sometimes works, but after refreshes, I can usually get some of the times on the page to end up being in EST instead of MST.

**Comment by hankeliu2015** [comment]
Hi, Like to give a try. Before getting into it, just make sure this is what you looking for. The CVS at LoveLand, CO suppose to show MSD time? Thanks!
![Screen Shot 2021-03-19 at 9 26 31 AM](https://user-images.githubusercontent.com/16155615/111804321-97031b80-8895-11eb-9a50-d7758558bebb.png)

**Comment by hankeliu2015** [comment]
![Screen Shot 2021-03-21 at 6 22 03 PM](https://user-images.githubusercontent.com/16155615/111923180-9324f400-8a63-11eb-9241-cbe9e5e69cb3.png)
Not able to duplicated above issue again today. But found the props <time:Sun Mar 21 2021 17:57:53 GMT-0400 (Eastern Daylight Time)> changes by my time zone settings. If I set my time to Denver, props value will change  to <time:Sun Mar 21 2021 15:57:53 GMT-0600 (Mountain Daylight Time)>.  I wonder this might affected DisplayLocalTime's computed property timeISO and timeLocale. 
![Screen Shot 2021-03-21 at 4 41 17 PM](https://user-images.githubusercontent.com/16155615/111923458-f19ea200-8a64-11eb-8de9-9a61bed5fb34.png)

**Comment by MoralCode** [comment]
@hankeliu2015 it seems to me based on the mention of refreshes that this issue is referring to the "flash" of a different timezone that occurs when an entry is reloaded, like is demonstrated by this video where the time periodically flashes as MDT before it updates itself:


https://user-images.githubusercontent.com/17362949/112079699-df446700-8b3d-11eb-8cd0-1d5f332c83d6.mp4

**Comment by hankeliu2015** [comment]
> @hankeliu2015 it seems to me based on the mention of refreshes that this issue is referring to the "flash" of a different timezone that occurs when an entry is reloaded, like is demonstrated by this video where the time periodically flashes as MDT before it updates itself:
> 
>  time.mp4

Thanks @MoralCode! Good catch. I noticed that was caused by computed property {{timeLocale}} loaded first,  a few milliseconds later, Time-Elements  converted the other computer property "timeISO" to PDT . 

I suspect the Vue props.time (see my previous screenshot from Vue devTool, tested with Denver/MDT time zone), which already converted the MDT time zone to my EST zone before passed to both computed properties. Somehow the timeLocale treat the props.time as EST but timeISO converted it to MDT.

Do not think I can do much on the 'flash', it seems just the "nature" how time-elements works. 

![Screen Shot 2021-03-22 at 9 57 21 PM](https://user-images.githubusercontent.com/16155615/112081700-77504980-8b5a-11eb-9452-7fcd3e44e82f.png)
![Screen Shot 2021-03-22 at 10 27 02 PM](https://user-images.githubusercontent.com/16155615/112083626-c6e44480-8b5d-11eb-830a-4a47b2a2425d.png)

**Comment by MoralCode** [comment]
It seems like this may be related: https://github.com/github/time-elements/issues/135

**Comment by hankeliu2015** [comment]
Hi @GUI , I am contacting time-elements team for troubleshooting. Mind answer them a question at <https://github.com/github/time-elements/issues/146#issuecomment-805920284> "This looks like a FOC - how is the component loaded? Do you have it dynamically imported, or perhaps in a deferred script tag within a large bundle? The time is updated when the JS kicks in."

**Comment by GUI** [comment]
Thanks so much everyone for looking into this! I'm not too sure what was going on, but I suspect it was something I was doing wrong in the configuration, or time-elements fighting with Nuxt/Vue. But as part of some broader revamps (https://github.com/GUI/covid-vaccine-spotter/commit/5e8efb7e715e9850bceb4cc69a33ebd82bd64953), I've actually changed things around in such a way that we shouldn't need time-elements anymore. I'm skipping the server-side rendering now, and just letting Vue handle the rendering, which means we can more simply use the client browser's time zone directly in Vue, rather than needing time-elements to contend with updating the server-rendered content.

So while I know this is a bummer not to really get to the root issue of what was going on before, I think this should be solved in a slightly different way now. But I really appreciate you all digging into this! But let me know if anyone's still seeing issues with the new implementation.

**Comment by hankeliu2015** [comment]
@GUI , thanks for explaining the logic behind. Looks great by using client's time zone. Just mention a minor issue. look like 'timeZone' could be removed from the component props. Tested on my local dev without it, all good. 
![Screen Shot 2021-03-25 at 12 45 09 PM](https://user-images.githubusercontent.com/16155615/112511588-f024f080-8d68-11eb-8d31-c0ffc2cd155f.png). Thanks!
