### ISSUE TITLE
Add new vaccine provider in CO:  Centura

### ISSUE THREAD

**Issue by tgeliot** [GUI/covid-vaccine-spotter#73]
See [https://www.centura.org/covid-19/covid-19-vaccine-information](https://www.centura.org/covid-19/covid-19-vaccine-information).
As of right (2021-03-17), they're scheduling appointments for mass immunizations at three locations in CO.  Near Denver, they're scheduling for 3/24.

**Comment by brandonmcclure** [comment]
I work at Denver Health in Colorado and we use the same EMR (Epic) as Centura. My coworkers and I have been doing some exploration on how we can surface our scheduling through this, although we are not quite at the same mass immunization point as Centrua. I am very interested in collaborating in surfacing this scheduling data in this or other web apps.

**Comment by GUI** [comment]
@tgeliot: Thanks so much for the heads up! I obviously hadn't been paying close enough to attention to some of these changes, since I was still thinking Centura, Denver Health, etc, were more in the "signup to be on a list" category (which I still think it is a great path to go down, just not something I've thought I can really help in scanning for appointment availability). But now that I see there's appointments that can be scheduled, I definitely want to try to add this! So thank you! I've given this site a quick look, and I think this information looks like it should be pretty scannable. 🤞 I unfortunately may not be able to get to this for a couple days, but I'm definitely hoping to get this added soon.

@brandonmcclure: If Denver Health has appointment availability that would be useful to integrate into Vaccine Spotter (or tools like it), I'd obviously love to collaborate! Let me know if you all end up publishing this type of data anywhere that I could access, or also happy to talk about this in more detail with you or your team. I really appreciate you all taking the time to look into this, not to mention everything else you all are doing to actually help get people vaccinated! So thank you!

**Comment by GUI** [comment]
Centra Health's Drive Up Events should now be scanned for appointment availability by Vaccine Spotter: https://www.vaccinespotter.org/CO/ There's nothing open right at this moment, but hopefully new slots will pop up and this will help. Thanks again or the suggestion, @tgeliot!

And @brandonmcclure, just give a shout if there's anything I can do to help add Denver Health appointment openings at any point.
